#server:
#  port: 17009
#
#spring:
#  application:
#    name: micro-service-consumer-ribbon
#
#eureka:
#  client:
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: micro-service-consumer-ribbon
  zipkin:
    base-url: http://localhost:9411