server:
  port: 7001


#eureka:
#  instance:
#    #eureka服务端的实例名称
#    hostname: localhost
#  server:
#    #关闭自我保护机制
#    enableSelfPreservation: false
#  client:
#    #false表示不向注册中心注册自己
#    registerWithEureka: false
#    #false自己就是注册中心，只查找注册进来的服务，不查找自己
#    fetchRegistry: false
#    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

eureka:
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411