server:
  port: 17000


#开发环境配置
spring:
  application:
    name: micro-service-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #mysql驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/clouddb01?useUnicode=true&useAffectedRows=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
  zipkin:
    base-url: http://localhost:9411
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dingding.springcloud.entity
  configuration:
    # 使用jdbc的getGeneratedKeys 可以获取数据库自增主键值
    use-generated-keys: true
    # 使用列别名替换列名，默认true。如：select name as title from table
    use-column-label: true
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true


#eureka:
#  client:
#    客户端注册进eureka服务列表
#    serviceUrl:
#      defaultZone: http://localhost:7001/eureka/
#    registerWithEureka: true
#    fetchRegistry: true
#  instance:
#    non-secure-port: ${server.port}




eureka:
  client:
#    客户端注册进eureka服务列表
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/


