
server:
  port: 9411


spring:
  application:
    name: micro-service-zipkin


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/


management:
  metrics:
    web:
      server:
        auto-time-requests: false